### ISSUE TITLE
[Doc]: Replace LLNL E3SM license with xCDAT license

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#419]
### Describe your documentation update

xCDAT was originally funded by E3SM and is now also funded by SEATS. xCDAT is in a position to have its own LLNL license.

The IM and software submission should be done within the next quarter because the review process can take weeks to months. Our goal is to have this completely done by the end of the year.

### TODO
- [x] Submit IM -- accepted
- [x] Submit xCDAT software (upload a zip?)
  - [ ] Find the website with step by step

Update Repo
- [x] Update README.rst file
  - New LLNL Release number
  - Update community section
  - Add code of conduct
- [x] Add NOTICE file
- [x] Add new open source LICENSE file (Apache 2-0 with LLVM Exception)
